rigetti/quil-rs

src/lib.rs
src/parser/common.rs
src/parser/error.rs
src/parser/lexer.rs
src/parser/mod.rs
src/program/graph.rs
src/program/mod.rs

Reduces the number of visible functions and type definitions to those reasonably needed for outside use. Notably, this means removing public visibility for raw parsing and lexing functions, while leaving access to useful constructs like `Program`, `ScheduledProgram`, and all `Instruction` members and variants.

Breaking: refine public API

---

src/program/graph.rs
src/program/mod.rs

This fixes an oversight from #2 which prevented access to necessary types in `program::graph`. That _could_ be fixed by re-exporting from `program` but there are enough of them, and they're cohesive around the concept of a `graph`, so I'll just expose the entire `graph` module itself.
I took the liberty of removing the `pub use graph::...` statement from the program module as well, which is a breaking change but in the interest of avoiding further confusion, I'll merge this as a fix and a patch version bump.

Make `program::graph` public

---

src/instruction.rs
src/parser/command.rs
src/parser/common.rs
src/parser/gate.rs

These two functions strike me as unnecessary (we can always use `nom::many0` directly) and a bit arbitrary (why `parse_qubits` but no `parse_gate_modifiers`, e.g.?).

Breaking: remove parse_qubits and parse_variable_qubits

---

src/instruction.rs
src/parser/command.rs
src/parser/instruction.rs
src/program/calibration.rs
src/program/mod.rs

Both `CalibrationDefinition` and `Instruction` have some unnecessary `Box`es—around a `Calibration` in the former and a `WaveformInvocation` in the latter. This PR removes them, so only `Expression`s have a `Box` in them (and this one is necessary due to recursive definitions).
Resolves #15, first observed in #11

Fix: Unbox calibrations and waveform invocations

---

.gitignore
src/parser/common.rs

First time using `nom` so let me know if there's a cleaner way to do this.

Fix: Allow indented comments when parsing.

---

src/instruction.rs
src/parser/command.rs
src/parser/instruction.rs

For the two frequency commands, [the spec] agrees with the previous structs in that they should take floats, but [pyQuil] allows expressions and does conversion on them, so I assume we should stick with that implementation.
[the spec]: https://github.com/quil-lang/quil/blob/master/rfcs/analog/spec_changes.md#frequency
[pyQuil]: https://github.com/rigetti/pyquil/blob/9545776eff57362aed18b619a36182c556b2296f/pyquil/api/_rewrite_arithmetic.py#L107

New: Support parsing SET-SCALE, SET-FREQUENCY, and SHIFT-FREQUENCY.

---

Cargo.toml
src/expression.rs
src/instruction.rs

If we don't mind relying on hashing for equality, this might work. Building off of @dbanty's work in #25, I've handwritten `impl Hash for Expression`. Basically, the strategy is
1. hashing the name of the enumeration variant (e.g. `"Address".hash(state)`), then
2. hashing the stuff inside (if any)
In the case of `Number(Complex<f64>)`, we turn the floats into their `u64` bit representation ([the docs claim this is reasonable](https://doc.rust-lang.org/std/primitive.f64.html#method.to_bits)) and hash that. In the case of an infix expression with a commutative operator (addition or multiplication), we order the operands by the u64 values of _their_ hashes.
I've also expanded the testing with [`proptest`](https://docs.rs/proptest/1.0.0/proptest/index.html) to demonstrate that for any two …

Upgrade: support equality between commutative expressions

---

src/parser/command.rs
src/parser/instruction.rs

A lot of these instructions are parsed exactly the same, so it feels kinda silly to have so many different functions to do it. Not sure how to deduplicate without just making it harder to use though so 🤷

New: Parse `SET-PHASE` and `SHIFT-PHASE`.

---

Cargo.toml
src/expression.rs
src/instruction.rs

This is to allow the pyQuil style of expression de-duplication by substitution. Allowing for use in a HashSet directly feels a lot better than a map of Expression.to_string() => Expression, and this way we can tweak how we differentiate between expressions (e.g. evaluating/simplifying automatically) at some point if we want to.
Note that Clippy is rightly angry about implementing `Hash` on something which has derived `PartialEq`. This is ultimately because we store floats in expressions and floats are not hashable. That problem can also lead to issues with equality anyway so I just ignored for now. The recommendation is to create a `PartialEq` implementation by hand that is guaranteed to have the same results as `Hash`.
We probably also want to do a custom PartialEq/Hash at some point …

Upgrade: impl Hash and Eq for Expression for use in deduplication.

---

src/instruction.rs
src/parser/command.rs
src/parser/gate.rs
src/parser/instruction.rs
src/program/calibration.rs
src/program/frame.rs
src/program/graph.rs
src/program/memory.rs
src/program/mod.rs

This enables stuff like
```
fn compile_gate(gate: Gate) -> Option<Vec<Gate>> { ... }
```
where before you would've needed
```
fn compile_gate(gate: Instruction) -> Option<Vec<Instruction>> {
match gate {
Gate { .. } => {
// ...
}
_ => // not a gate :(
}
}
```
It does make some stuff more verbose, but generally I think that's constrained to library code, and not consumer code.
Closes #21

Breaking: Instruction variants are top-level structs

---

Cargo.lock

This PR is to trigger a release, after learning about the semantics of our semantic-release automation. However, it will also act as a test to see if the automation updates & adds `Cargo.lock` to a commit prior to release (effectively making the same kind of change in this PR).

Update: latest Cargo.lock version

---

.github/workflows/bench.yml
.gitmodules
Cargo.lock
Cargo.toml
benches/parser.rs
deny.toml

Partially satisfying #36, this PR adds automated benchmarks running `criterion.rs` harness to parse several `quil` programs used as tests in the `quilc` repository. `quilc` has been included as a git submodule of this repository.

Update: add automated benchmarks for parsing quilc test programs

---

.github/workflows/bench.yml
benches/parser.rs

Simplify & correct the download/archive flow for benchmark results. Each PR will be benchmarked against the current `base` result. When the branch is `main`, the `base` result is archived for use in the next workflow run. 
Upon merging to `main`, the benchmark should run again and archive its results.

test use of criterion default baselines with archive

---

.gitmodules

This caused an issue in CI, which doesn't have an SSH key to provide for github auth. Unnecessary anyway -- the quilc repo is public.

Fix: change quilc submodule to use HTTPS

---

src/instruction.rs
src/parser/command.rs
src/parser/common.rs
src/parser/instruction.rs
src/program/graph.rs
src/program/memory.rs
src/program/mod.rs

Adds support for `EQ, LT, LE, GT, GE` instructions as per [Quil spec #6-5Classical-Instructions](https://quil-lang.github.io/#6-5Classical-Instructions)

feat: support ternary logic instructions

---

src/expression.rs

In using this library elsewhere, I've noticed folks doing something like
```rust
match x {
case Expression::Number(x) if x.im == 0.0 => {
...
},
...
}
```
which to me seems
1. repetitive, since we'd like to just match on a real number and move on with our lives; and
2. error-prone, since it's conceivable (however unlikely) that we might have an expression that algebraically _should_ be a real number but has a non-zero but _wicked_ tiny imaginary part due to rounding issues from other computation.
This PR creates `Expression.to_real() -> Result<f64, EvaluationError>` and adds two descriptive types of `EvaluationError`.

Add Expression.to_real()

---

Cargo.lock
Cargo.toml
src/expression.rs
src/instruction.rs
src/parser/command.rs
src/program/calibration.rs
src/program/error.rs
src/program/graph.rs
src/program/mod.rs

Significant changes here which are necessary but not sufficient for downstream compilation.
Note that calibration expansion here, while improved from previous, is not at parity with either the spec or pyQuil. That could be finished here or left to a later PR.

Improve Program Calibration

---

src/instruction.rs
src/parser/instruction.rs
src/parser/lexer.rs
src/program/calibration.rs

closes #80 
Simple fix with a test case for regression. See issue for context.

Fix: DEFCAL MEASURE serialization

---

src/program/error.rs
src/program/mod.rs

Closes #86.
This adds a few variants to the public `Program::Error` enumeration and uses them for the possible `Err`s coming off of `Program::from_str`.

Breaking: Use a proper error type for Program::from_str

---

src/program/type_check.rs

I accidentally left in a `dbg!` in #88.

Fix: remove a `dbg!` statement left over from #88

---

src/expression.rs
src/instruction.rs
src/parser/common.rs
src/parser/error/input.rs
src/parser/expression.rs
src/parser/instruction.rs
src/parser/lexer/mod.rs
src/parser/macros.rs
src/parser/mod.rs
src/parser/token.rs
src/program/mod.rs

This is another performance improvement. Ish.
When running benchmarks in `dev`/`debug` mode, this showed a 35% decrease in runtime (edit: 26% when I generated HTML reports) on the sample-calibrations file (parse in ~2.33s rather than ~3.6s). It also showed a ~15% improvement on most corpus files, but ~8% regression on three of them.
When running in normal `bench` mode (basically release), the story is a bit different. Before these changes, parsing the sample calibrations file happened in ~223ms on avg, and ~239ms after these changes (~7% regression). Corpus files also showed a single-digit-percent performance regression.
OTOH, the sample calibrations had 15% outliers in the initial run and 5.6% outliers after applying changes. I am not sure whether criterion includes the outliers in …

Fix: do not get line/column info for tokens except on error

---

src/instruction.rs
src/program/frame.rs
src/program/mod.rs

Simple approach:
- Expand calibrations
- Remove calibrations
- Scan through instructions and keep only the frames and waveforms used by at least one instruction
Did not address memory references given that a full simplification of those would reduce shrinking them to the minimum size (removing unnecessary capacity), and there's some complexity there. On top of that, too many memory regions is not as common of a problem as is thousands of lines of unused calibrations.

Program.into_simplified

---

src/instruction.rs
src/program/frame.rs
src/program/graph.rs
src/program/mod.rs

Simple approach to RESET frame calculation support as described in the issue.
Reviewers:
- Does this approach make sense?
- Are there cases in which "overly greedy" blocking of frames as computed here in `quil-rs` will cause issues in compilation or elsewhere downstream?
Closes #33 
Linked to #128 for use in tandem downstream.

Frame calculations for RESET

---

src/instruction.rs
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__pulse_after_capture.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__simple_capture.snap

fix: Waveforms w/o params need no parens

---

src/parser/expression.rs
src/parser/lexer/mod.rs
src/program/calibration.rs

Closes #141 
This adds one test case, which currently fails:
```
failures:
---- program::calibration::tests::expansion stdout ----
thread 'program::calibration::tests::expansion' panicked at 'assertion failed: `(left == right)`
left: `"DELAY q 4e-8\n"`,
right: `"DELAY 0 4e-8\n"`', src/program/calibration.rs:407:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and subsequently modifies `CalibrationSet.expand` to handle `DELAY` instructions similarly to `GATE` instructions.

Fix: correctly expand delays

---

src/instruction.rs
src/program/graph.rs
src/program/graphviz_dot.rs
src/program/mod.rs
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__active_reset_single_frame.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__blocking_2q_pulse.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__blocking_pulses_after_nonblocking.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__blocking_pulses_wrap_nonblocking.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__chained_pulses.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__different_frames_blocking.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__different_frames_nonblocking.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__fence_all.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__fence_all_with_nonblocking_pulses.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__fence_one_wrapper.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__jump.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__parametric_pulse.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__parametric_pulses_using_capture_results.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__pulse_after_capture.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__pulse_after_set_frequency.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__simple_capture.snap
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__single_dependency.snap

Closes #185 
Introduces `ExecutionDependency::Timing` as described in the issue, with updated snapshot tests to reflect the change.

feat!: introduce ExecutionDependency::Scheduled

---

src/instruction.rs
src/parser/command.rs
src/parser/common.rs
src/parser/instruction.rs
src/parser/lexer/mod.rs
src/program/frame.rs
src/program/mod.rs

- Adds a parser for SWAP-PHASES with a test
- Covers the parser with a test case previously limited to the lexer - a "kitchen sink" program. That had a SWAP-PHASES instruction all along, which lexed fine ... as a gate.
- This exposed two failures in parsing that program:
- `DEFGATE Name as PERMUTATION` incorrectly had a second line. Permutation-type gate definitions have a single-line block. Fixed the test case.
- `DELAY 0 1` exposed an edge case in parsing delays which is now handled - the `1` should be interpreted as the duration rather than a qubit index, even though the two parsers overlap on integers.
- Fixes `SWAP-PHASES` frame matching by adding `FrameMatchCondition::Or`
Closes https://github.com/rigetti/quil-rs/issues/199

fix: parse SWAP-PHASES

---

src/instruction.rs
src/program/snapshots/quil_rs__program__graphviz_dot__tests__graph__pulse_after_set_frequency.snap

Closes #202 
Several instructions don't participate directly in the pulse program, but should still be scheduled relative to instructions which do. This is important for FREQUENCY and PHASE operations especially, because their effects vary depending on when they are executed. It is not enough to ensure correct ordering, as `main` does today.

fix: mark additional instructions as scheduled

---

Cargo.lock
Cargo.toml
deny.toml
src/expression.rs

fix: The imaginary part of a complex number will now always be formatted as a floating point number.

---

src/expression.rs
src/parser/expression.rs

fix: The parser now follows the correct precedence rules for ungrouped infix expressions

---

quil-rs/Cargo.toml
quil-rs/benches/corpus.rs
quil-rs/benches/scheduled_program_from_program.rs
quil-rs/src/expression.rs
quil-rs/src/program/graph.rs

Another round of performance improvements!
This one is focused primarily on improving the performance of `ScheduledProgram::from_program` and `terminate_working_block`, a function that it calls.
Existing benchmarks `parser` and `get_frames_for_instruction` are largely unchanged with a little bit of noise in either direction. The new benchmark for `ScheduledProgram::from_program` shows no significant performance change at worst and a 16%/1.2µs improvement (from 7.4 to 6.2).
Further, an internal project shows a similar case of no significant change at worst and an improvement of 6.7%/55µs (from 814.24 to 759.69)

refactor: optimize terminate_working_block

---

quil-py/src/instruction/classical.rs
quil-rs/src/instruction/classical.rs
quil-rs/src/parser/command.rs
quil-rs/src/parser/instruction.rs

Per the quil spec, the destination is the left most argument.

fix: The destination and source are no longer flipped when parsing CONVERT instructions.

---

quil-rs/src/expression.rs
quil-rs/src/instruction/gate.rs
quil-rs/src/parser/command.rs
quil-rs/src/parser/instruction.rs
quil-rs/src/program/calibration.rs
quil-rs/src/program/frame.rs
quil-rs/src/program/graph.rs
quil-rs/src/program/memory.rs
quil-rs/src/program/mod.rs

Another set of optimizations, focused on searching for patterns in the code (e.g. cloning, creating a `Vec`) and seeing if it can be easily optimized in some way.
Each commit was benchmarked separately using an internal project, where any changes with negative results were discarded. I then ran benchmarks for both this project and the internal one, comparing `main` with this branch. The following summarizes the difference between `main` and these changes:
- `ScheduledProgram::from_program` saw a small performance increase overall, roughly 1-3%
- The `parser` saw little change in performance. Notably, only two example programs were called out as significant by `cargo bench`:
- `empty-quil.quil` had a regression of 2.9% (~0.04 µs)
- `good-include.quil` had a regression of 16% (~1.5 µs)
- …

refactor!: optimize clones and collections

---

knope.toml

This PR follows the advice from the [broken build step in the pipeline](https://github.com/rigetti/quil-rs/actions/runs/5328135255/jobs/9652408753).

ci: ignore Cargo.lock in prerelease

---

quil-py/src/program/mod.rs
quil-rs/benches/get_frames_for_instruction.rs
quil-rs/src/instruction/mod.rs
quil-rs/src/program/frame.rs
quil-rs/src/program/graph.rs
quil-rs/src/program/graphviz_dot.rs
quil-rs/src/program/memory.rs
quil-rs/src/program/mod.rs

There are two primary changes here:
1. The qubits used by a `Program` is now tracked when adding instructions using `add_instruction(s)`. This removes the need to built the `HashSet` whenever the set of qubits is requested.
- The downside is that the `instructions` field should no longer be `pub` to avoid accidentally working around this behavior. This is my next step.
- This change introduced an improvement of 5-7% in the relevant benchmarks, and no difference otherwise.
2. `ScheduledProgram::from_program` used to take a `&Program` and clone the parts it needed. It now instead takes references to those things, removing the excess clones.
- With real-world programs, this saw a ~14% improvement in benchmarking. A few benchmark programs saw improvements of ~60%! (I'm not sure how much I …

refactor!: more optimizations

---

quil-rs/benches/get_frames_for_instruction.rs
quil-rs/src/instruction/mod.rs
quil-rs/src/program/frame.rs
quil-rs/src/program/graph.rs
quil-rs/src/program/mod.rs

* Call this method less frequently
* Return `Option::None` rather than `HashSet::new` when nothing matches
Evaluation against a yet-to-be-published benchmark indicates a 50% performance increase in `ScheduledProgram::from_program`
Closes #231

perf!: optimize Program::get_frames_for_instruction

---

quil-rs/src/program/calibration.rs
quil-rs/src/program/frame.rs
quil-rs/src/program/mod.rs

Closes #241 
Simple enough.
I did not see a neat way to share code between `Program::into_instructions` and `Program::to_instructions` without cloning more than strictly needs to be cloned in the latter.
I'd like to be able to support `as_instructions(&self) -> Vec<&Instruction>` but many of the owned instructions are created within the method (and not just referenced). If `CalibrationSet` et al were to be restructured so as to maintain their backing instructions in `Instruction` form (rather than decomposing them), we could do that (in another PR).

feat(rs): Program::into_instructions

---

quil-rs/src/expression/mod.rs
quil-rs/src/expression/simplification.rs
quil-rs/src/program/calibration.rs
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Literal-Parameter.snap

This change makes expression simplification consistent between the following:
* `pi` is the root expression
* `pi` is a member of the expression
Previously, `pi/2` simplified to its floating point form (`1.57...`) while `pi` did not. This amends that, so that `simplify(pi) == 3.14...`).

fix(rs): 'simplify' pi expression to floating-point form

---

deny.toml
quil-rs/src/program/calibration.rs
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@ShiftPhase.snap

Closes #227 - calibration expansion was actually working fine, we just weren't account for every type of instruction that could be in the calibration.

fix: Expand all analog control instructions

---

quil-rs/src/expression/mod.rs
quil-rs/src/expression/simplification.rs

Adds rules to the `egg` ruleset with tests to validate behavior.
Closes https://github.com/rigetti/quil-rs/issues/244

feat(rs): associate & commute in expression simplification

---

quil-rs/Cargo.toml
quil-rs/README.md

Adds `wasm-bindgen` crate feature so that users don't have to discover themselves that `egg` requires `instant` which requires the same feature to be set.
Also adds a feature table to the Readme.

feat(rs): wasm-bindgen cargo feature

---

Cargo.lock
quil-rs/Cargo.toml

We recently added code that only compiles with Rust 1.70, leading to a confusing error message ([reported in Slack](https://rigetti.slack.com/archives/C02BBP9A60J/p1689182934952119)).
This sets the minimum required Rust version to 1.70 for `quil-rs`. For now, no change is made to `quil-py`. If we frequently break Rust version compatibility for users, we should consider using a tool to automate setting the version; [this one](https://github.com/foresterre/cargo-msrv) looks promising.

Specify minimum rust version to improve compile-failure error message

---

quil-rs/src/instruction/frame.rs
quil-rs/src/instruction/gate.rs
quil-rs/src/instruction/pragma.rs
quil-rs/src/parser/lexer/quoted_strings.rs

Adds escaping for the two special characters, and a round-trip table test to validate.
Edit: the original version had a bug which made the escaping a no-op; this prompted me to realize that Debug formatting of strings basically just does what we need. "Basically" because it also escapes unicode graphemes, which is not called for in the Quil spec, but it's also not contrary to the Quil spec and could save us a bug report in the future.
Closes #257.

fix(rs): escape Quil strings for display

---

quil-rs/src/expression/mod.rs

Simple fix: the `format_inner_expression` call was missing from nested infix expression stringification.

fix(rs): infix expression parenthesization

---

Cargo.lock
quil-rs/benches/scheduled_program_from_program.rs
quil-rs/src/instruction/mod.rs
quil-rs/src/program/frame.rs
quil-rs/src/program/graph.rs
quil-rs/src/program/graphviz_dot.rs
quil-rs/src/program/mod.rs

This adds a couple simple getters that are needed for an internal project and should be generally useful for any consumers of `quil-rs`.
Edit: this expanded from the initial PR, but with the same goal of allowing custom handling of instructions when scheduling, especially for `PRAGMA` instructions.

feat!: allow overriding Instruction getters

---

quil-py/quil/instructions/__init__.pyi
quil-py/src/instruction/calibration.rs
quil-py/src/instruction/circuit.rs
quil-py/src/instruction/classical.rs
quil-py/src/instruction/control_flow.rs
quil-py/src/instruction/declaration.rs
quil-py/src/instruction/frame.rs
quil-py/src/instruction/gate.rs
quil-py/src/instruction/measurement.rs
quil-py/src/instruction/mod.rs
quil-py/src/instruction/pragma.rs
quil-py/src/instruction/reset.rs
quil-py/src/instruction/timing.rs
quil-py/src/instruction/waveform.rs
quil-py/src/program/mod.rs
quil-py/test/instructions/test_copy.py
quil-rs/src/instruction/mod.rs

It's not uncommon to want to create a copy of something using Python's copy module, so this makes all instruction types compatible with it.

feat(python): Instruction classes now implement `__copy__`, and `__deepcopy__`, making them compatible with Python's `copy` module.

---

quil-rs/src/parser/common.rs
quil-rs/src/parser/lexer/mod.rs

fix: Allow whitespace to delimit matrix specifications, better support parsing  identifiers followed by a minus operator.

---

quil-rs/src/instruction/mod.rs
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Param-Precedence.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Variable-Qubit.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@ShiftPhase.snap

In [this pyQuil issue](https://github.com/rigetti/pyquil/issues/1673), we saw that the v3 version of pyQuil can't parse `DEFCALS` with a variable qubit; e.g.
```
DEFCAL I %q:
DELAY q 4e-8
```
would cause pyQuil to crash, complaining about the `%` symbol. While the [spec claims](https://quil-lang.github.io/#12-6Defining-Calibrations) this is a valid way of writing variable qubits for calibrations, the percent symbol prefix is only otherwise used for parameters (e.g. angles for rotational gates), not for qubits themselves. This PR changes how variable qubits are printed, removing the `%` prefix.
If this change is merged into `quil-rs`, chances are we probably want to update the spec accordingly as well.

fix: no percent symbol in variable qubit outputs

---

quil-rs/src/instruction/frame.rs
quil-rs/src/instruction/mod.rs
quil-rs/src/instruction/pragma.rs
quil-rs/src/parser/lexer/quoted_strings.rs
quil-rs/src/parser/token.rs

Fixes #315.
This uses a new `QuotedString` wrapper with a custom `Display` impl to only escape quotation marks and backslashes in strings, and nothing else.

fix: use internal QuotedString wrapper to quote Quil strings correctly

---

quil-py/quil/program/__init__.pyi
quil-py/src/program/mod.rs
quil-rs/src/program/mod.rs
quil-rs/src/program/snapshots/quil_rs__program__tests__wrap_in_loop.snap

feat: Add `Program.wrap_in_loop()` method

---

.github/workflows/publish-quil-py.yml
quil-rs/src/instruction/calibration.rs
quil-rs/src/parser/mod.rs

closes #326
This repo has been setup as a trusted publisher for `quil` in PyPI. I've modified the workflow per the [maturin documentation](https://www.maturin.rs/distribution.html?highlight=trusted%20p#using-pypis-trusted-publishing).

ci: Use trusted publishing for PyPI

---

quil-rs/src/instruction/mod.rs

fix: `is_quil_t()` now correctly returns false for WAIT instructions

---

quil-py/pyproject.toml

Adding a documentation link to pyproject.toml makes it so that repositories like PyPI can link to them on packages page.

docs: Provide documentation link to pyproject.toml

---

quil-rs/src/expression/mod.rs
quil-rs/src/program/frame.rs
quil-rs/src/program/mod.rs

Reverts rigetti/quil-rs#300
The existing implementation appears to have been correct:
```
DELAY 0 1 matches frame 0 "rf" -> no
DELAY 0 matches frame 0 "rf" -> yes
DELAY 0 1 matches frame 0 1 "rf" -> yes
DELAY 0 1 matches frame 0 "rf" -> no
```
Quil spec:
> If frame names are specified, then the delay instruction affects those frames on those qubits. If no frame names are specified, all frames on precisely those qubits are affected.
```
match := {frame_qubits} == {delay_qubits}
```

Revert "fix(quil-rs): match exactly one qubit for DELAYs without frame specifier"

---

.github/workflows/publish-quil-py.yml
Cargo.lock

To support `qcs-sdk-rust` builds to `ppc64le`.
See https://github.com/rigetti/qcs-sdk-rust/pull/449

build: build linux ppc64le wheel

---

Cargo.lock
Cargo.toml
README.md
deny.toml
knope.toml
quil-cli/Cargo.toml
quil-cli/src/main.rs
quil-rs/Cargo.toml
quil-rs/src/program/mod.rs
quil-rs/src/reserved.rs

I often find myself wanting to quickly test the behavior of the parser. Right now that requires setting up some boilerplate in either pyQuil or quil-rs to go through the parser. This CLI exposes the functionality more directly, allowing me to bisect issues quicker.
In addition to using the parser, I see this as a useful entry point for the recent program analysis feature. It also enables easier benchmarking with tools like hyperfine. Not that the existing benchmarks aren't sufficient, but it makes benching new programs or expressions a bit more accessible and faster in the iteration phase.
closes #349

feat(quil-cli): Add CLI for interacting with quil-rs

---

Cargo.lock
Cargo.toml
quil-py/Cargo.toml
quil-py/quil/program/__init__.pyi
quil-py/src/program/calibration.rs
quil-py/src/program/mod.rs
quil-rs/Cargo.toml
quil-rs/src/instruction/calibration.rs
quil-rs/src/instruction/mod.rs
quil-rs/src/program/calibration.rs
quil-rs/src/program/calibration_set.rs
quil-rs/src/program/mod.rs
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Measure-Calibration.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Precedence-Fixed-Match.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Precedence-No-Qubit-Match.snap

I've reworked `CalibrationSet` to actually be a set, where existence in the set is keyed on the calibrations "signature" (e.g. the fields determine the instructions they expand into). In addition, the set maintains insertion order, but disregards order during equality checks. This is to keep program serialization deterministic, while recognizing that the order of calibrations doesn't matter in the semantic meaning of the program.
This required a custom data structure for a few reasons:
1. We care about calibration equality on two different levels: "signature" and equality of contents. This makes using something like an `IndexSet` impossible. To prevent duplicate signatures in a set, we'd have to defined `Hash` and thus `Eq` in terms of the signature. However, when comparing the equality …

fix!: CalibrationSet's and Program's will be considered equal if they contain the same set of calibrations, regardless of order.

---

quil-rs/src/program/calibration_set.rs
quil-rs/src/program/mod.rs

fix: Program equality is sensitive to the order of calibration instructions.

---

.github/workflows/msrv.yml
quil-py/Makefile.toml
quil-py/make_docs.py
quil-py/poetry.lock
quil-py/pyproject.toml
quil-py/quil/__init__.py
quil-py/quil/expression/__init__.pyi
quil-py/quil/instructions/__init__.py
quil-py/quil/instructions/__init__.pyi
quil-py/quil/program/__init__.py
quil-py/quil/program/__init__.pyi
quil-py/quil/validation/__init__.py
quil-py/quil/validation/identifier.pyi
quil-py/src/program/analysis.rs
quil-py/src/program/scheduling.rs
quil-py/test/instructions/test_copy.py
quil-py/test/instructions/test_gate.py
quil-py/test/program/test_program.py
quil-py/test/test_eq.py
quil-rs/src/program/analysis/control_flow_graph.rs

closes #358 
supports rigetti/pyquil#1770

feat: Support getting and constructing BasicBlocks.

---

quil-py/quil/program/__init__.pyi

Tiny docs fixes:
* Remove the second argument from the call in the example
* Remove the note about zero-duration instructions
* Add a note about the necessary DEFCALs

chore: fix BasicBlock#as_schedule_seconds documentation

---

Cargo.lock
quil-rs/src/waveform/templates.rs

The MSRV Clippy check was failing; looks like `std::f64::EPSILON` is now `f64::EPSILON`.

chore: remove deprecated `f64` constants to satisfy Clippy

---

Cargo.lock
quil-rs/src/instruction/mod.rs
quil-rs/src/program/mod.rs

Users of `quil-rs` can use `InstructionHandler` to override how instructions are associated with frames, but this is not considered by `Program::into_simplified`. This PR adds a method, `InstructionHandler::simplify_program`, that uses the frame matching of `InstructionHandler` to determine which frames to retain in the program.

feat: allow using instruction handler when simplifying program

---

quil-py/test/program/__snapshots__/test_program.ambr
quil-rs/src/instruction/calibration.rs
quil-rs/src/instruction/circuit.rs
quil-rs/src/instruction/frame.rs
quil-rs/src/instruction/gate.rs
quil-rs/src/instruction/snapshots/quil_rs__instruction__circuit__test_circuit_definition__display@CircuitDefinition No Params.snap
quil-rs/src/instruction/snapshots/quil_rs__instruction__circuit__test_circuit_definition__display@CircuitDefinition With Params.snap
quil-rs/src/instruction/snapshots/quil_rs__instruction__circuit__test_circuit_definition__display@CircuitDefinition With Single Param.snap
quil-rs/src/instruction/snapshots/quil_rs__instruction__gate__test_gate_definition__display@Parameterized GateDefinition.snap
quil-rs/src/instruction/snapshots/quil_rs__instruction__gate__test_gate_definition__display@Pauli Sum GateDefinition.snap
quil-rs/src/instruction/snapshots/quil_rs__instruction__gate__test_gate_definition__display@Permutation GateDefinition.snap
quil-rs/src/instruction/snapshots/quil_rs__instruction__waveform__test_waveform_definition__display@Simple WaveformDefinition.snap
quil-rs/src/instruction/waveform.rs
quil-rs/src/parser/lexer/mod.rs
quil-rs/src/program/mod.rs
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Instruction-Match.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Literal-Parameter.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Param-Precedence.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Simple.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@Calibration-Variable-Qubit.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@FenceVariableQubit.snap
quil-rs/src/program/snapshots/quil_rs__program__calibration__tests__expansion@ShiftPhase.snap
quil-rs/src/program/snapshots/quil_rs__program__tests__filter_instructions.snap
quil-rs/src/program/snapshots/quil_rs__program__tests__wrap_in_loop.snap
quil-rs/src/quil.rs
quil-rs/tests/snapshots/calibration_test__calibration_cz.quil.snap
quil-rs/tests/snapshots/calibration_test__calibration_cz_phase.quil.snap
quil-rs/tests/snapshots/calibration_test__calibration_rx.quil.snap
quil-rs/tests/snapshots/calibration_test__calibration_xy.quil.snap

feat!: Use 4 spaces for indentation.

---

Cargo.lock
deny.toml
quil-rs/Cargo.toml

Closes #337. The `lexical-core` crate recently released version 1.0.0, and it appears that with this release, the security vulnerabilities in `lexical` have been addressed, so we no longer need to choose a new dependency.
Supersedes #387.

fix: update lexical

---

.github/workflows/release.yml
Cargo.lock

knope action v1 cannot install versions newer than 0.10

fix: update knope action to v2

---

quil-py/tests_py/program/test_program.py
quil-rs/src/program/analysis/control_flow_graph.rs
quil-rs/src/program/scheduling/schedule.rs

`ScheduledBasicBlock::get_waveform_duration_seconds` previously assumed that the duration of all built-in waveforms is equal to their duration parameter.  This isn't true for `erfsquare`, though; the `duration` parameter just specifies the duration of the active pulse, and the `padleft` and `padright` parameters specify silent padding on either side which contribute to the total duration.
This PR updates the computation of the duration to include the padding.  This is a breaking change, because now scheduling a program with an `erfsquare` waveform requires that the `erfsquare` waveform have these extra parameters and that they be constants.  Indeed, some of our very own tests were broken by this.
There is also some inconsistency in names, which this PR papers over by accepting both:
* The …

fix!: correctly compute duration for `erfsquare` waveform templates

---

Cargo.lock
quil-rs/proptest-regressions/expression/mod.txt
quil-rs/src/parser/lexer/mod.rs
quil-rs/src/parser/mod.rs
quil-rs/src/parser/token.rs
quil-rs/src/reserved.rs

Fix the tokenization of identifiers and keywords so that keywords are not parsed within word boundaries.  Previously, `BITS` would be parsed as the data type `BIT` followed by the identifier `S`; now, it is correctly parsed as the single identifier `BITS`.
This also fixes the tokenization of `NaN`, `Inf`, and `Infinity`; previously, these were case-insensitively parsed as floats (with the same incorrect prefix behavior, so `nana` would parse as the float `NaN` followed by the identifier `a`), but now they are correctly parsed as normal identifiers.
Finally, this PR makes the "mut" keyword lowercase-only.
Closes #427

fix!: tokenize keywords and identifiers correctly

---

Cargo.lock
quil-rs/proptest-regressions/expression/mod.txt
quil-rs/src/expression/mod.rs

This is the easiest way to resolve #316 in a way that doesn't break the API (the other way being to use `OrderedFloat`).
Fixes #316.

fix!: make NaN == NaN inside Expression

---

quil-py/pyproject.toml
quil-py/quil/instructions/__init__.pyi
quil-py/src/instruction/calibration.rs
quil-py/tests_py/instructions/test_gate.py

See https://github.com/rigetti/quil-rs/issues/420
It was always intended for these to be getters, this fixes the implementation and types.

fix(py)!: make Calibration and MeasureCalibrationDefinition getter methods into properties

---

.github/workflows/publish-quil-py.yml

Closes #436 
See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact

fix(py): github release action configuration for upload and download artifact v4

---

.github/workflows/publish-quil-py.yml

A follow up to https://github.com/rigetti/quil-rs/pull/437

fix(py): github actions should use macos-latest build runner

---

quil-rs/src/expression/simplification/by_hand.rs
quil-rs/src/expression/simplification/mod.rs
quil-rs/src/instruction/waveform.rs

Now, expression simplification will try to simplify `a / (b * c)` to `(a / b) / c`.
Previously, it would try to simplify to `(a / b) * c` instead.
(Expression simplification already correctly simplifies `(x * y) / z` to `x * (y / z)`.)

fix: fix simplification so that a/(bc) = (a/b)/c

---

Cargo.lock
deny.toml
quil-py/Cargo.toml
quil-py/src/expression.rs
quil-rs/Cargo.toml
quil-rs/src/expression/mod.rs
quil-rs/src/expression/simplification/by_hand.rs
quil-rs/src/expression/simplification/mod.rs
quil-rs/src/instruction/gate.rs
quil-rs/src/parser/command.rs
quil-rs/src/parser/common.rs
quil-rs/src/parser/expression.rs
quil-rs/src/parser/instruction.rs
quil-rs/src/program/calibration.rs

This PR features changes to the representation of expressions and simplification in order to:
1. Obtain structural sharing/perform common subexpression elimination: recursive expression structures are now wrapped in [`ArcIntern<Expression>`](https://docs.rs/internment/latest/internment/struct.ArcIntern.html), so that there is at most one instance of every expression; expressions with common subterms will have pointers to the same value.
2. Use this structural sharing to make simplification more efficient by caching work, so that simplification is performed at most once per expression per simplification pass.
This produces a ×10+ speedup on some translation workloads.

Expression interning

---

deny.toml
quil-py/pyproject.toml
quil-py/src/instruction/declaration.rs
quil-rs/Cargo.toml
quil-rs/src/instruction/mod.rs
quil-rs/src/program/analysis/control_flow_graph.rs
quil-rs/src/program/mod.rs
quil-rs/src/program/type_check.rs

This edits `quil-py`'s `pyproject.toml` to target Python versions 3.9 through 3.12 and sets `numpy>=1.26`, since the previous version combination wasn't accurate and could cause build errors during dependency solving.
Closes: #449

fix!: set Python and dependency versions to match

---

Cargo.lock
quil-py/quil/waveforms/__init__.pyi
quil-py/src/waveforms.rs
quil-py/tests_py/conftest.py
quil-py/tests_py/test_waveforms.py

Adds missing constructors to the waveforms classes. This is essentially the same as the #423 and #424, but against the updated dependencies.
Closes: #422

feat(quil-py): add waveform constructors

---

.github/workflows/release.yml
Cargo.lock
knope.toml
quil-rs/src/parser/mod.rs
quil-rs/src/program/scheduling/graph.rs

This commit updates `knope.toml` so that the automatically-generated release commits contain the necessary changes to `Cargo.lock`.

ci: update Cargo.lock when releasing

---

quil-rs/src/instruction/mod.rs
quil-rs/src/program/frame.rs
quil-rs/src/program/mod.rs
quil-rs/src/program/scheduling/graph.rs

feat!: improvements to `MatchedFrames` and related methods
