rigetti/quil-rs

- src/expression.rs
- src/parser/lexer.rs
> Fix parsing/printing double precision

- Cargo.toml
To avoid conflicts with the other project without downgrading that one.
> Update: num-complex to 0.4.0

- src/instruction.rs
Immediate motivation is to solve an issue in `qcs-sdk-rust` where programs with pragmas fail to run on `qvm`. I also handled a `// FIXME` comment I found in the area though.
> Fix: PRAGMA instruction `Display` impl

- .github/workflows/release.yml
- package.json
Should resolve broken CI noted here: https://github.com/rigetti/quil-rs/runs/7011559513
> Fix: update node version and dependencies for semantic-release

- src/parser/command.rs
(Illustrates a test simplification within the scope of a PR)
> Simplify parse_defgate test case

- src/parser/lexer/mod.rs
> Fix: identifier parser

- src/parser/error/error.rs
> fix: require dynamic error to by Send

- src/parser/command.rs
- src/parser/lexer/error.rs
- src/parser/lexer/mod.rs
- src/parser/lexer/quoted_strings.rs
> fix: support escaped double quotes and backslashes in strings

- src/parser/error/error.rs
> fix: make dynamic error `Sync` as well

- src/expression.rs
> feat: Support Expression arithmetic operations

- src/program/mod.rs
> Support add_instructions and From<Vec<Instruction>> for Program

- deny.toml
- src/parser/command.rs
- src/program/calibration.rs
- src/program/frame.rs
> allow for variable qubit in DEFCAL MEASURE

- quil-py/src/instruction/classical.rs
- quil-rs/src/instruction/classical.rs
- quil-rs/src/instruction/mod.rs
> fix: BinaryLogic now has it's own to string implementation

- quil-py/src/program/mod.rs
- quil-rs/src/program/mod.rs
> fix!: When adding two Programs, the resulting Program will have a correct used qubit cache.

- quil-py/src/program/mod.rs
- quil-rs/src/program/mod.rs
Does what it says on the tin. Adds an AddAssign impl to Program that doesn't clone the left hand side.
> feat: Make in-place addition of Program more efficient

- Cargo.lock
- quil-rs/src/instruction/control_flow.rs
- quil-rs/src/instruction/qubit.rs
> fix: implement PartialOrd correctly for types implementing Ord

- Cargo.lock
- quil-rs/src/instruction/mod.rs
> fix: calibration definitions don't contribute to Instrution::get_qubits

- Cargo.lock
- quil-rs/src/program/memory.rs
> fix: add missing instruction memory accesses

- .github/workflows/msrv.yml
- .github/workflows/publish-quil-py.yml
- Cargo.lock
- quil-py/Cargo.toml
> feat(py): Support Python 3.12

- quil-rs/src/instruction/frame.rs
Simple approach, copied from `MemoryReference`, where it's been quite useful in practice.
> feat(quil-rs): impl FromStr for FrameIdentifier

- quil-rs/src/program/mod.rs
- quil-rs/src/program/snapshots/quil_rs__program__tests__wrap_in_loop.snap
> fix: The `wrap_in_loop` method now applies the end target to the program

- quil-rs/src/instruction/circuit.rs
- quil-rs/src/instruction/snapshots/quil_rs__instruction__circuit__test_circuit_definition__display@CircuitDefinition With Single Param.snap
> fix: include separators between DEFCIRCUIT parameters

- Cargo.lock
- knope.toml
- quil-cli/Cargo.toml
- quil-py/Cargo.toml
- quil-py/src/instruction/frame.rs
- quil-py/src/instruction/waveform.rs
- quil-py/src/program/mod.rs
- quil-rs/src/instruction/frame.rs
- quil-rs/src/instruction/mod.rs
- quil-rs/src/instruction/waveform.rs
- quil-rs/src/parser/common.rs
- quil-rs/src/parser/instruction.rs
- quil-rs/src/program/mod.rs
- quil-rs/src/program/type_check.rs
> feat!: Program instruction iteration and serialization is deterministic.

- quil-rs/src/expression/mod.rs
Fixes https://github.com/rigetti/quil-rs/issues/367
> test: handle nan in proptest cases

- quil-py/pyproject.toml
> Set numpy version to 1.21

- Cargo.lock
- quil-rs/src/instruction/extern_call.rs
- quil-rs/src/program/mod.rs
Addresses moving clippy error: https://github.com/rigetti/quil-rs/actions/runs/11636418174/job/32407785492
>  allow return of offending pragma in error
